class Flowlayer < Formula
  desc "FlowLayer local process orchestration for development workflows"
  homepage "https://flowlayer.tech"
  version "1.0.0"

  # Generated by scripts/release-sync.sh
  # Release tag: v1.0.0
  # Sources:
  # - Server: FlowLayer/flowlayer
  # - TUI: FlowLayer/tui
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-server-1.0.0-macos-arm64.tar.gz"
      sha256 "11479a2f60f5aad22933591821199fde368a3c7553146c1d6614a7dd3de8a824"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/tui/releases/download/v1.0.0/flowlayer-client-tui-1.0.0-macos-arm64.tar.gz"
        sha256 "3872e2b4e9d12fcf936b742fdf95b515239a7457aba86d62d193f211736eaafc"
      end
    else
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-server-1.0.0-macos-amd64.tar.gz"
      sha256 "20708e6cf0ddcb9f33c38d55b099b0d96eaf8a93354fab362bcf9d781ded4980"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/tui/releases/download/v1.0.0/flowlayer-client-tui-1.0.0-macos-amd64.tar.gz"
        sha256 "11f0d8cfeb9797bc90dc297ef6c9c7ca619b640f3096bb9e55bc21083209dcc2"
      end
    end
  elsif OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-server-1.0.0-linux-arm64.tar.gz"
      sha256 "6fa1b87803b1bda28b29ee86f33862c357302095e900470c0a92907c9a50469e"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/tui/releases/download/v1.0.0/flowlayer-client-tui-1.0.0-linux-arm64.tar.gz"
        sha256 "29725bb27decd109868b80641ef5c1b0a94ba4d0ab69e037b4b6812451a8f32d"
      end
    else
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-server-1.0.0-linux-amd64.tar.gz"
      sha256 "c363cc28528d22bbf0fbd9246e7849beb17c37e7aa8f6d04a76d4416c98243c3"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/tui/releases/download/v1.0.0/flowlayer-client-tui-1.0.0-linux-amd64.tar.gz"
        sha256 "43580a69548f001bbe9477f38583236fb6002a05ab082d686ec7a9e6f56c9001"
      end
    end
  end

  def install
    server_bin = Dir["**/flowlayer-server"].first
    odie "flowlayer-server binary not found in archive" unless server_bin
    bin.install server_bin => "flowlayer-server"

    resource("flowlayer-client-tui").stage do
      client_bin = Dir["**/flowlayer-client-tui"].first
      odie "flowlayer-client-tui binary not found in resource archive" unless client_bin
      bin.install client_bin => "flowlayer-client-tui"
    end
  end

  test do
    system "#{bin}/flowlayer-server", "--version"
    system "#{bin}/flowlayer-client-tui", "--version"
  end
end
