class Flowlayer < Formula
  desc "FlowLayer local process orchestration for development workflows"
  homepage "https://flowlayer.tech"
  version "1.0.0"

  # Generated by scripts/release-sync.sh
  # Release tag: v1.0.0
  # URLs and SHA256 values must come from published release artifacts.
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer_darwin_arm64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256_FROM_RELEASE_SHA256SUMS"
    else
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer_darwin_amd64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256_FROM_RELEASE_SHA256SUMS"
    end
  elsif OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer_linux_arm64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256_FROM_RELEASE_SHA256SUMS"
    else
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer_linux_amd64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256_FROM_RELEASE_SHA256SUMS"
    end
  end

  def install
    bin.install "flowlayer-server"
    bin.install "flowlayer-client-tui"
  end

  test do
    system "#{bin}/flowlayer-server", "--version"
    system "#{bin}/flowlayer-client-tui", "--version"
  end
end
