class Flowlayer < Formula
  desc "FlowLayer local process orchestration for development workflows"
  homepage "https://flowlayer.tech"
  version "1.0.0"

  # Generated by scripts/release-sync.sh
  # Release tag: v1.0.0
  # Assets are published from the global FlowLayer release: FlowLayer/flowlayer.
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-server-1.0.0-macos-arm64.tar.gz"
      sha256 "acfede29d1803251e3460f6ae5735993ac6864936c5b9b5f02f6bbdd0fdb1860"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-client-tui-1.0.0-macos-arm64.tar.gz"
        sha256 "7a68db80f8e3272a1525eb51760212923fc7cc7bea865037661f6ddfbc2afaa9"
      end
    else
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-server-1.0.0-macos-amd64.tar.gz"
      sha256 "729c1980449ae2a83d655ee574f459cec0e6c3958616074f87f08f2b6e950c71"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-client-tui-1.0.0-macos-amd64.tar.gz"
        sha256 "d5df986eb37c6eb29aa7db4da2cc686488f40e9168b347304bdf9dfd29aeddd0"
      end
    end
  elsif OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-server-1.0.0-linux-arm64.tar.gz"
      sha256 "4dc1a70ab69c56ab382e814d7e14bf1db1b8be26f2d38a4c8088e937bf0a3b94"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-client-tui-1.0.0-linux-arm64.tar.gz"
        sha256 "f1014855ec512633c034e130fbe5b7e1a21d2c86719c20355f23fec53a73a929"
      end
    else
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-server-1.0.0-linux-amd64.tar.gz"
      sha256 "7455b100e605d32d9bffbc1edf6061702b79a31c5e2cdeab6d4dda228e9643de"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/flowlayer/releases/download/v1.0.0/flowlayer-client-tui-1.0.0-linux-amd64.tar.gz"
        sha256 "9c65d57c8147c3287e68fd406535943052ed10a8c9b04f8983fc81ee1a541109"
      end
    end
  end

  def install
    server_bin = Dir["**/flowlayer-server"].first
    odie "flowlayer-server binary not found in archive" unless server_bin
    bin.install server_bin => "flowlayer-server"

    resource("flowlayer-client-tui").stage do
      client_bin = Dir["**/flowlayer-client-tui"].first
      odie "flowlayer-client-tui binary not found in resource archive" unless client_bin
      bin.install client_bin => "flowlayer-client-tui"
    end
  end

  test do
    system "#{bin}/flowlayer-server", "--version"
    system "#{bin}/flowlayer-client-tui", "--version"
  end
end
