class Flowlayer < Formula
  desc "FlowLayer local process orchestration for development workflows"
  homepage "https://flowlayer.tech"
  version "1.1.0"

  # Generated by scripts/release-sync.sh
  # Release tag: v1.1.0
  # Assets are published from the global FlowLayer release: FlowLayer/flowlayer.
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.1.0/flowlayer-server-1.1.0-macos-arm64.tar.gz"
      sha256 "2eaa9b7096971dac9f6ebdf1b7369babb04b946d26726c14afd52eb647beabbd"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/flowlayer/releases/download/v1.1.0/flowlayer-client-tui-1.1.0-macos-arm64.tar.gz"
        sha256 "f7e8adc38e70cfbbd5ea47cc135f82d67165ea5cf1b0cf56708f3419da7ee0f0"
      end
    else
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.1.0/flowlayer-server-1.1.0-macos-amd64.tar.gz"
      sha256 "f84f32f771cec76f75b5f259af1b54db794903be69b55d6b6a5761790c04d7eb"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/flowlayer/releases/download/v1.1.0/flowlayer-client-tui-1.1.0-macos-amd64.tar.gz"
        sha256 "386369811b0372fb049bdcb69393dbc7b61110f74d74fd0d1fb6c61180762bcc"
      end
    end
  elsif OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.1.0/flowlayer-server-1.1.0-linux-arm64.tar.gz"
      sha256 "cc4f9e93f3fd686c50f26632171d5aca7d28a6533dcdc1a263fe5e478b1a1b44"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/flowlayer/releases/download/v1.1.0/flowlayer-client-tui-1.1.0-linux-arm64.tar.gz"
        sha256 "67227fe51a69b49b5f5c4d677926e5abe7088398187a55df6e2cbccc7cdef06d"
      end
    else
      url "https://github.com/FlowLayer/flowlayer/releases/download/v1.1.0/flowlayer-server-1.1.0-linux-amd64.tar.gz"
      sha256 "f24b4d18ebf917bbce9e14a1ad89271dd3bf3f4f966aa91230cd60be3ad415bd"

      resource "flowlayer-client-tui" do
        url "https://github.com/FlowLayer/flowlayer/releases/download/v1.1.0/flowlayer-client-tui-1.1.0-linux-amd64.tar.gz"
        sha256 "3bca8931ebf4c5fae779e518e6df2467e17b1a080004cd41b91278c639392996"
      end
    end
  end

  def install
    server_bin = Dir["**/flowlayer-server"].first
    odie "flowlayer-server binary not found in archive" unless server_bin
    bin.install server_bin => "flowlayer-server"

    resource("flowlayer-client-tui").stage do
      client_bin = Dir["**/flowlayer-client-tui"].first
      odie "flowlayer-client-tui binary not found in resource archive" unless client_bin
      bin.install client_bin => "flowlayer-client-tui"
    end
  end

  test do
    system "#{bin}/flowlayer-server", "--version"
    system "#{bin}/flowlayer-client-tui", "--version"
  end
end
