class Flowlayer < Formula
  desc "FlowLayer local process orchestration for development workflows"
  homepage "https://flowlayer.tech"
  version "{{VERSION}}"

  # Generated by scripts/release-sync.sh
  # Release tag: {{RELEASE_TAG}}
  # URLs and SHA256 values must come from published release artifacts.
  if OS.mac?
    if Hardware::CPU.arm?
      url "{{DARWIN_ARM64_URL}}"
      sha256 "{{DARWIN_ARM64_SHA256}}"
    else
      url "{{DARWIN_AMD64_URL}}"
      sha256 "{{DARWIN_AMD64_SHA256}}"
    end
  elsif OS.linux?
    if Hardware::CPU.arm?
      url "{{LINUX_ARM64_URL}}"
      sha256 "{{LINUX_ARM64_SHA256}}"
    else
      url "{{LINUX_AMD64_URL}}"
      sha256 "{{LINUX_AMD64_SHA256}}"
    end
  end

  def install
    bin.install "flowlayer-server"
    bin.install "flowlayer-client-tui"
  end

  test do
    system "#{bin}/flowlayer-server", "--version"
    system "#{bin}/flowlayer-client-tui", "--version"
  end
end
