class Flowlayer < Formula
  desc "FlowLayer local process orchestration for development workflows"
  homepage "https://flowlayer.tech"
  version "{{VERSION}}"

  # Generated by scripts/release-sync.sh
  # Release tag: {{RELEASE_TAG}}
  # Sources:
  # - Server: FlowLayer/flowlayer
  # - TUI: FlowLayer/tui
  if OS.mac?
    if Hardware::CPU.arm?
      url "{{SERVER_DARWIN_ARM64_URL}}"
      sha256 "{{SERVER_DARWIN_ARM64_SHA256}}"

      resource "flowlayer-client-tui" do
        url "{{TUI_DARWIN_ARM64_URL}}"
        sha256 "{{TUI_DARWIN_ARM64_SHA256}}"
      end
    else
      url "{{SERVER_DARWIN_AMD64_URL}}"
      sha256 "{{SERVER_DARWIN_AMD64_SHA256}}"

      resource "flowlayer-client-tui" do
        url "{{TUI_DARWIN_AMD64_URL}}"
        sha256 "{{TUI_DARWIN_AMD64_SHA256}}"
      end
    end
  elsif OS.linux?
    if Hardware::CPU.arm?
      url "{{SERVER_LINUX_ARM64_URL}}"
      sha256 "{{SERVER_LINUX_ARM64_SHA256}}"

      resource "flowlayer-client-tui" do
        url "{{TUI_LINUX_ARM64_URL}}"
        sha256 "{{TUI_LINUX_ARM64_SHA256}}"
      end
    else
      url "{{SERVER_LINUX_AMD64_URL}}"
      sha256 "{{SERVER_LINUX_AMD64_SHA256}}"

      resource "flowlayer-client-tui" do
        url "{{TUI_LINUX_AMD64_URL}}"
        sha256 "{{TUI_LINUX_AMD64_SHA256}}"
      end
    end
  end

  def install
    server_bin = Dir["**/flowlayer-server"].first
    odie "flowlayer-server binary not found in archive" unless server_bin
    bin.install server_bin => "flowlayer-server"

    resource("flowlayer-client-tui").stage do
      client_bin = Dir["**/flowlayer-client-tui"].first
      odie "flowlayer-client-tui binary not found in resource archive" unless client_bin
      bin.install client_bin => "flowlayer-client-tui"
    end
  end

  test do
    system "#{bin}/flowlayer-server", "--version"
    system "#{bin}/flowlayer-client-tui", "--version"
  end
end
