# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
# Generated by scripts/release-sync.sh
# Release tag: {{RELEASE_TAG}}

PackageIdentifier: FlowLayer.FlowLayer
PackageVersion: {{VERSION}}
InstallerType: zip
NestedInstallerType: portable
Installers:
  - Architecture: x64
    InstallerUrl: {{WINGET_WINDOWS_AMD64_URL}}
    InstallerSha256: {{WINGET_WINDOWS_AMD64_SHA256}}
    NestedInstallerFiles:
      - RelativeFilePath: flowlayer-server.exe
        PortableCommandAlias: flowlayer-server
      - RelativeFilePath: flowlayer-client-tui.exe
        PortableCommandAlias: flowlayer-client-tui
  - Architecture: arm64
    InstallerUrl: {{WINGET_WINDOWS_ARM64_URL}}
    InstallerSha256: {{WINGET_WINDOWS_ARM64_SHA256}}
    NestedInstallerFiles:
      - RelativeFilePath: flowlayer-server.exe
        PortableCommandAlias: flowlayer-server
      - RelativeFilePath: flowlayer-client-tui.exe
        PortableCommandAlias: flowlayer-client-tui
ManifestType: installer
ManifestVersion: 1.10.0