# Generated by scripts/release-sync.sh
# Release tag: {{RELEASE_TAG}}
# This template is not publishable until URLs and SHA256 values are replaced.

PackageIdentifier: FlowLayer.FlowLayer
PackageVersion: {{VERSION}}
PackageName: FlowLayer
Publisher: FlowLayer
License: TODO-VERIFY-LICENSE
ShortDescription: FlowLayer local process orchestration for development workflows
Installers:
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: {{WINDOWS_AMD64_URL}}
    InstallerSha256: {{WINDOWS_AMD64_SHA256}}
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: flowlayer-server.exe
        PortableCommandAlias: flowlayer-server
      - RelativeFilePath: flowlayer-client-tui.exe
        PortableCommandAlias: flowlayer-client-tui
  - Architecture: arm64
    InstallerType: zip
    InstallerUrl: {{WINDOWS_ARM64_URL}}
    InstallerSha256: {{WINDOWS_ARM64_SHA256}}
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: flowlayer-server.exe
        PortableCommandAlias: flowlayer-server
      - RelativeFilePath: flowlayer-client-tui.exe
        PortableCommandAlias: flowlayer-client-tui
ManifestType: singleton
ManifestVersion: 1.6.0
