# Generated by scripts/release-sync.sh
# Release tag: {{RELEASE_TAG}}
# Draft only: current release assets are split across two repositories and two zip files.
# Winget portable manifests are cleanly publishable when a single bundle contains both
# flowlayer-server.exe and flowlayer-client-tui.exe for each architecture.
# Recommendation: publish a future Windows bundle asset per arch, then switch this
# manifest to that single archive.

PackageIdentifier: FlowLayer.FlowLayer
PackageVersion: {{VERSION}}
PackageName: FlowLayer
Publisher: FlowLayer
License: TODO-VERIFY-LICENSE
ShortDescription: FlowLayer distribution draft. Winget publication currently blocked by split server and TUI archives.
Installers:
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: {{SERVER_WINDOWS_AMD64_URL}}
    InstallerSha256: {{SERVER_WINDOWS_AMD64_SHA256}}
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: flowlayer-server.exe
        PortableCommandAlias: flowlayer-server
    # TUI companion archive metadata (not installable as second portable archive in one manifest):
    # URL: {{TUI_WINDOWS_AMD64_URL}}
    # SHA256: {{TUI_WINDOWS_AMD64_SHA256}}
  - Architecture: arm64
    InstallerType: zip
    InstallerUrl: {{SERVER_WINDOWS_ARM64_URL}}
    InstallerSha256: {{SERVER_WINDOWS_ARM64_SHA256}}
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: flowlayer-server.exe
        PortableCommandAlias: flowlayer-server
    # TUI companion archive metadata (not installable as second portable archive in one manifest):
    # URL: {{TUI_WINDOWS_ARM64_URL}}
    # SHA256: {{TUI_WINDOWS_ARM64_SHA256}}
ManifestType: singleton
ManifestVersion: 1.6.0
