# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json
# Generated by scripts/release-sync.sh
# Release tag: {{RELEASE_TAG}}

PackageIdentifier: FlowLayer.FlowLayer
PackageVersion: {{VERSION}}
PackageLocale: en-US
Publisher: FlowLayer
PackageName: FlowLayer
License: Proprietary
ShortDescription: Local process orchestration for development workflows.
Description: FlowLayer installs flowlayer-server and flowlayer-client-tui for local development orchestration workflows.
PackageUrl: https://flowlayer.tech
PublisherUrl: https://flowlayer.tech
ManifestType: defaultLocale
ManifestVersion: 1.10.0