# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json
# Generated by scripts/release-sync.sh
# Release tag: {{RELEASE_TAG}}

PackageIdentifier: FlowLayer.FlowLayer
PackageVersion: {{VERSION}}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0